# Project Config
site_name:    delgoodie
site_url:     https://delgoodie.github.io
site_author:  William Del Giudice
copyright:    Copyright &copy; 2016 - 2024 delgoodie
site_description: General knowledgebase from delgoodie
repo_name:        delgoodie/delgoodie.github.io
repo_url:         https://github.com/delgoodie/delgoodie.github.io
edit_uri:         blob/master/docs/


# Site Config
docs_dir:           docs
use_directory_urls: true
strict:             true


theme: 
  name: material
  language: en
  features:
    - navigation.tabs
    - navigation.top
    - navigation.instant
    - navigation.indexes
    - search.suggest
    - search.highlight
    - search.share
    - content.code.copy
    - content.action.edit
    - content.action.view
    - toc.follow
    # - navigation.expand
    # - navigation.tabs.sticky
    # - toc.integrate

  palette:
    - media: "(prefers-color-scheme: dark)"
      scheme: ayu
      # primary: indigo
      # accent:  indigo
      toggle:
        icon: material/weather-night
        name: Dark Mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      # primary: indigo
      # accent: indigo
      toggle:
        icon: material/flare
        name: Light Mode
  font:
    # text: Nunito
    text: Source Serif Pro
    code: Source Code Pro
  icon:
    logo: material/delta
    repo: fontawesome/brands/github
    edit: material/file-edit-outline
    view: material/file-eye-outline
  favicon: _site/favicon.ico



# Theme Customization
extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/delgoodie
    - icon: fontawesome/brands/youtube
      link: https://youtube.com/@delgoodie
  # analytics:
  #   provider: google
  #   property: G-VWCEPP5L4L



# Markdown Extensions
markdown_extensions:
  # ThirdParty Extensions
  - mdx_breakless_lists

  # Python Markdown
  - markdown.extensions.abbr
  - markdown.extensions.admonition
  - markdown.extensions.attr_list
  - markdown.extensions.def_list
  - markdown.extensions.footnotes
  - markdown.extensions.tables
  - markdown.extensions.md_in_html
  - markdown.extensions.toc:
      slugify: !!python/object/apply:pymdownx.slugs.slugify {kwds: {case: lower}} ###revisit
      permalink: "#"
      toc_depth: 6
  - markdown.extensions.meta       ###revisit
  - markdown.extensions.nl2br      ###revisit
  - markdown.extensions.sane_lists ###revisit
  # - markdown.extensions.smarty:  ###revisit
  #     smart_quotes: false

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg