name: compress-and-resize-images
on:
  workflow_dispatch:
  # push:
  #   branches:
  #     - master
  #   paths:
  #     - 'docs/**/_assets/**'

jobs:
  compress:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
      - uses: namoscato/action-tinify@v1
        with:
          api_key: ${{ secrets.TINIFY_API_KEY }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          resize_width: 1024
